name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      env:
        # JFrog platform url (for example: https://acme.jfrog.io)
        JF_URL: https://soleng.jfrog.io 
      with:
        # Name of the OIDC provider as specified on the OIDC integration page in the JFrog Platform
        oidc-provider-name: tomokim-github-actions-integration 
        oidc-audience: tomokim-github-actions-integration
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
  
    - name: Check JFrog connectivity
      run: |
        # Ping the server
        jf rt ping
        # Collect environment variables for the build
        jf rt bce
        # Collect VCS details from git and add them to the build
        jf rt bag

    - name: Run tests and build project
      run: mvn clean package

    #- name: Upload to JFrog Artifactory
    #  run: |
    #    # Upload JAR files to Artifactory
    #    jf rt upload "target/*.jar" "tomokim-dev-backend-local-maven-dev-japan/com/example/maven-sample/1.0.0-SNAPSHOT/"
    #    # Publish build info
    #    jf rt bp
